version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:nightly-stretch
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./pigallery2/config:/app/data/config"
      - "db-data:/app/data/db"
      - "./pigallery2/images:/app/data/images"
      - "./pigallery2/tmp:/app/data/tmp"
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
